# Site settings
title: DevDrivel
email: devdrivel@city-driving.co.uk
description: > # this means to ignore newlines until "baseurl:"
  DevDrivel, the [TC] Gaming development blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://devdrivel.tc-gaming.co.uk" # the base hostname & protocol for your site
twitter_username: TCCityDriving
github_username:  TC-Gaming
excerpt_separator: <!--more-->
paginate: 10

# Build settings
markdown: redcarpet

# kramdown settings
kramdown:
  input: GFM

gems: [jekyll-paginate]
