# Site settings
title: DevDrivel
email: devdrivel@city-driving.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://devdrivel.tc-gaming.co.uk" # the base hostname & protocol for your site
twitter_username: TCCityDriving
github_username:  TC-Gaming
paginate: 10

# Build settings
markdown: kramdown
